stages:
  - lint
  - test
  - build
  - deploy
linter:
  stage: lint
  image: python:latest
  before_script:
    - export username=$submodule_username
    - export token=$submodule_token
    - sed -i 's/ssh:\/\/git/https:\/\/'"$username"':'"$token"'/g' .gitmodules
    - sed -i 's/ssh:\/\/git/https:\/\/'"$susername"':'"$token"'/g' .git/config
    - git submodule update --init --recursive
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-server:test
  before_script:
    - sed -i 's/ssh:\/\/git/https:\/\/$submodule_username:$submodule_token/g' .gitmodules
    - sed -i 's/ssh:\/\/git/https:\/\/$submodule_username:$submodule_token/g' .git/config
    - git submodule update --init --recursive
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-server-test
build_prod:
  stage: build
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-server:exe
  only:
    - master
  before_script:
    - sed -i 's/ssh:\/\/git/https:\/\/$submodule_username:$submodule_token/g' .gitmodules
    - sed -i 's/ssh:\/\/git/https:\/\/$submodule_username:$submodule_token/g' .git/config
    - git submodule update --init --recursive
  script:
    - make build_lib_prod
    - make build_prod
    - cp exe/build/pwire-server .
  artifacts:
    expire_in: 14 days
    paths:
      - pwire-server      
deploy:
  stage: deploy
  trigger: epj/2020/pwire/pwire-installer
