stages:
  - lint
  - test
  - build
linter:
  stage: lint
  image: python:latest
  before_script:
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-server:test
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-server-test
build_prod:
  stage: build
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-server:exe
  only:
    - master
#Install boost dependency
    - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
    - tar -zxf boost_1_72_0.tar.gz
    - cd boost_1_72_0/
    - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - ./bootstrap.sh --prefix=/usr/arm-linux-gnueabihf/ --with-libraries=system
    - "sed -i 's/using gcc ;/using gcc : arm : arm-linux-gnueabihf-g++ ;/g' project-config.jam"
    - ./b2 link=static
    - ./b2 headers
    - cp stage/lib/libboost_system.a /usr/arm-linux-gnueabihf/lib/
    - cp -r boost /usr/arm-linux-gnueabihf/include/
    - cd ..
#/Install
  script:
    - make build_lib_prod
    - make build_prod
  artifacts:
    expire_in: 14 days
    paths:
      - exe/build/pwire-server