stages:
  - lint
  - test
  - build
linter:
  stage: lint
  image: python:latest
  before_script:
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-server:test
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-server-test
build_prod:
  stage: build
  image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-server:exe
  only:
    - master
  script:
    - make build_lib_prod
    - make build_prod
  artifacts:
    expire_in: 14 days
    paths:
      - exe/build/pwire-server