stages:
  - lint
  - test
  - build
linter:
  stage: lint
  image: python:latest
  before_script:
    - pip install cpplint
  script:
    - make lint
unit_tests:
  stage: test
  image: gcc:latest
  script:
    - make build_test
    - make run_test
  artifacts:
    expire_in: 1 day
    paths:
      - test/build/pwire-server-test
build_prod:
  stage: build
  image: gcc:latest
  only:
    - master
  before_script:
    - apt update
    - apt install libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
#Install cpp-redis dependency
    - apt install git
    - apt install cmake
    - git clone https://github.com/cpp-redis/cpp_redis.git
    - cd cpp_redis
    - git submodule init && git submodule update
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - make install
    - cd /
#/Install
#Install boost dependency
  script:
    - make build_lib_prod
    - make build_prod
  artifacts:
    expire_in: 14 days
    paths:
      - exe/build/pwire-server